#!/usr/bin/env bash

set -euxo pipefail

mk() { mkdir -p "${1}" && chmod 777 "${1}"; }

mk '/var/tmp/npm'

if [ "${1}" = 'start' ]; then
	mkdir -p "${HOME}/.npm"
	ln -s '/var/tmp/npm' "${HOME}/.npm/_cacache"
fi

if [ "${1}" = 'stop' ]; then
	rm -f "${HOME}/.npm/_cacache"
fi
